routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('driverr', 'DriverController');
Route::resource('transportt', 'TransportController');

app/Driver.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use \App\Transport;

class Driver extends Model
{
    protected $fillable = [
        'name', 'birth_date'
    ];
//    /**
//     * @var int $id ID
//     */
//    public $id;
//
//    /**
//     * @var string $name Name
//     */
//    public $name;
//
//    /**
//     * @var \DateTimeImmutable $birthDate Birth date
//     */
//    public $birthDate;
//
//    public $createdAt;
//
//    public $updatedAt;

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasOne
     */
    public function transport()
    {
        return $this->hasOne('App\Transport');
    }
}

app/Http/Controllers/DriverController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Driver;
use PhpParser\Node\Expr\Array_;

class DriverController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

        /** @var array $drivers */
        $drivers = Driver::all();

        return view('drivers.index',['drivers'=>compact('drivers')]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('drivers.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name'       => 'required',
            'birth_date' => 'required|date',
        ]);
        $driver = new Driver([
            'name'       => $request->get('name'),
            'birth_date' => $request->get('birth_date'),
        ]);

        $driver->save();

        return redirect()
            ->route('driverr.index')
            ->with('success', 'Водитель добавлен');
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $driver = Driver::find($id);

        return view('/drivers/edit', compact('driver'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'name'=>'required',
            'birth_date'=> 'required|date',
        ]);

        $driver = Driver::find($id);
        $driver->name = $request->get('name');
        $driver->birth_date = $request->get('birth_date');
        $driver->save();

        return redirect('/driverr')->with('success', 'Информация о водителе была изменена успешно');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $driver = Driver::find($id);
        $driver->delete();

        return redirect('/driverr')->with('success', 'Водитель был удалён успешно');
    }
}

resources/views/drivers/create.blade.php
@extends('drivers.layout')

@section('content')
    <style>
        .uper {
            margin-top: 40px;
        }
    </style>
    <div class="card uper">
        <div class="card-header">
            Добавить водителя
        </div>
        <div class="card-body">
            @if ($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div><br/>
            @endif
            <form method="post" action="{{ route('driverr.store') }}">
            <div class="form-group">
            @csrf
            <label for="name">Name:</label>
            <input type="text" class="form-control" name="name"/>
            </div>
            <div class="form-group">
            <label for="price">BirthDate :</label>
            <input type="date" class="form-control" name="birth_date"/>
            </div>
            <button type="submit" class="btn btn-primary">Add</button>
            </form>
        </div>
    </div>
@endsection

resources/views/drivers/edit.blade.php
@extends('drivers.layout')
@section('content')
    <style>
        .uper {
            margin-top: 40px;
        }
    </style>
    <div class="card uper">
        <div class="card-header">
            Изменить информацию о водителе
        </div>
        <div class="card-body">
            @if ($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div><br />
            @endif
            <form method="post" action="{{ route('driverr.update', $driver->id) }}">
                @method('PATCH')
                @csrf
                <div class="form-group">
                    <label for="name">Имя:</label>
                    <input type="text" class="form-control" name="name" value={{ $driver->name }} />
                </div>
                <div class="form-group">
                    <label for="price">Дата рождения:</label>
                    <input type="date" class="form-control" name="birth_date" value={{ $driver->birth_date }} />
                </div>
                <button type="submit" class="btn btn-primary">Изменить</button>
            </form>
        </div>
    </div>
@endsection

resources/views/drivers/index.blade.php
@extends('drivers.layout')
@section('content')
    <div class="container">
        <style>
            .uper {
                margin-top: 40px;
            }
        </style>
        <a class="uper">
            @if(session()->get('success'))
                <div class="alert alert-success">
                    {{ session()->get('success') }}
                </div><br/>
            @endif
            <a href="{{route('driverr.create')}}"><button class="btn btn-success">Создать</button></a>
            <table class="table table-striped">
                <thead>
                <tr>
                    <td>Имя</td>
                    <td>День рождения</td>
                    <td></td>
                    <td></td>
                </tr>
                </thead>
                <tbody>
                @foreach($drivers['drivers'] as $driver)

                    <tr>
                        <td>{{$driver->name}}</td>
                        <td>{{$driver->birth_date}}</td>
                        <td><a href="{{ route('driverr.edit',$driver->id)}}" class="btn btn-primary">Изменить</a></td>
                        <td>
                            <form action="{{ route('driverr.destroy', $driver->id)}}" method="post">
                                @csrf
                                @method('DELETE')
                                <button class="btn btn-danger" type="submit">Удалить</button>
                            </form>
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div>
    </div>
@endsection

resources/views/drivers/layout.blade.php
@extends('layouts.app')