routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('driverr', 'DriverController');
Route::resource('transportt', 'TransportController');

app/Transport.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Transport extends Model
{
    protected $fillable = ['brand', 'mileage', 'driver_id', 'type_id', 'status_id'];

    public function driver()
    {
        return $this->belongsTo('App\Driver');
    }

    public function type()
    {
        return $this->belongsTo('App\TransportType', 'type_id');
    }

    public function status()
    {
        return $this->belongsTo('App\TransportStatus', 'status_id');
    }
}

app/TransportType.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class TransportType extends Model
{
    protected $table = 'transport_type';
}

app/Http/Controllers/TransportController.php
<?php

namespace App\Http\Controllers;

use App\Driver;
use App\Transport;
use App\TransportStatus;
use App\TransportType;
use Illuminate\Http\Request;

class TransportController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        /** @var array $transports */
        $transports = Transport::all();

        return view('transports.index', ['transports' => compact('transports')]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $drivers = Driver::all();
        $statuses = TransportStatus::all();
        $types = TransportType::all();

        //dd($drivers);

        return view('transports.create', [
            'drivers'  => $drivers,
            'statuses' => $statuses,
            'types'    => $types
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'brand'   => 'required',
            'mileage' => 'required|int',
            'driver_id' => 'required|int',
            'status_id' => 'required|int',
            'type_id' => 'required|int',
        ]);
        $transport = new Transport([
            'brand'   => $request->get('brand'),
            'mileage' => $request->get('mileage'),
            'driver_id' => $request->get('driver_id'),
            'status_id' => $request->get('status_id'),
            'type_id' => $request->get('type_id'),
        ]);

        $transport->save();

        return redirect()
            ->route('transportt.index')
            ->with('success', 'Транспорт добавлен');
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $transport = Transport::find($id);
        $drivers = Driver::all();
        $statuses = TransportStatus::all();
        $types = TransportType::all();

        //dd($drivers);

        return view('transports.edit', [
            'transport'=>$transport,
            'drivers'  => $drivers,
            'statuses' => $statuses,
            'types'    => $types
        ]);

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'brand'     => 'required',
            'mileage'   => 'required|int',
            'driver_id' => 'required|int',
            'type_id'   => 'required|int',
            'status_id' => 'required|int',
        ]);

        $transport = Transport::find($id);
        $transport->brand = $request->get('brand');
        $transport->mileage = $request->get('mileage');
        $transport->driver_id = $request->get('driver_id');
        $transport->status_id = $request->get('status_id');
        $transport->type_id = $request->get('type_id');
        $transport->save();

        return redirect('/transportt')->with('success', 'Информация об автомобиле была изменена успешно');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $transport = Transport::find($id);
        $transport->delete();

        return redirect('/transportt')->with('success', 'Автомобиль был удалён успешно');
    }
}

resources/views/transports/create.blade.php
@extends('transports.layout')

@section('content')
    <div class="card uper">
        <div class="card-header">
            Добавить транспорт
        </div>
        <div class="card-body">
            @if ($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div><br/>
            @endif
            <form method="post" action="{{ route('transportt.store') }}">
                <div class="form-group">
                    @csrf
                    <label for="name">Марка:</label>
                    <input type="text" class="form-control" name="brand"/>
                </div>
                <div class="form-group">
                    <label for="mileage">Пробег :</label>
                    <input type="number" class="form-control" name="mileage"/>
                </div>
                <div class="form-group">
                    <label for="driver_id">Водитель:</label>
                    <select class="form-control" name="driver_id">
                        @foreach ($drivers as $driver)
                            <option value="{{$driver->id}}">{{$driver->name}}</option>
                        @endforeach
                    </select>
                </div>
                <div class="form-group">
                    <label for="type_id">Тип:</label>
                    <select class="form-control" name="type_id">
                        @foreach ($types as $type)
                            <option value="{{$type->id}}">{{$type->name}}</option>
                        @endforeach
                    </select>
                </div>
                <div class="form-group">
                    <label for="status_id">Статус:</label>
                    <select class="form-control" name="status_id">
                        @foreach ($statuses as $status)
                            <option value="{{$status->id}}">{{$status->name}}</option>
                        @endforeach
                    </select>
                </div>
                <button type="submit" class="btn btn-primary">Добавить</button>
            </form>
        </div>
    </div>
@endsection

resources/views/transports/edit.blade.php
@extends('transports.layout')

@section('content')
    <style>
        .uper {
            margin-top: 40px;
        }
    </style>
    <div class="card uper">
        <div class="card-header">
            Изменить информацию об автомобиле
        </div>
        <div class="card-body">
            @if ($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div><br/>
            @endif
            <form method="post" action="{{ route('transportt.update', $transport->id) }}">
                @method('PATCH')
                @csrf
                <div class="form-group">
                    <label for="brand">Марка:</label>
                    <input type="text" class="form-control" name="brand" value={{ $transport->brand}} />
                </div>
                <div class="form-group">
                    <label for="mileage">Пробег:</label>
                    <input type="number" class="form-control" name="mileage" value={{ $transport->mileage }} />
                </div>
                <div class="form-group">
                    <label for="driver_id">Водитель:</label>
                    <select class="form-control" name="driver_id">
                        @foreach ($drivers as $driver)
                            <option value="{{$driver->id}}">{{$driver->id}}</option>
                        @endforeach
                    </select>
                </div>
                <div class="form-group">
                    <label for="type_id">Тип:</label>
                    <select class="form-control" name="type_id">
                        @foreach ($types as $type)
                            <option value="{{$type->id}}">{{$type->name}}</option>
                        @endforeach
                    </select>
                </div>
                <div class="form-group">
                    <label for="status_id">Статус:</label>
                    <select class="form-control" name="status_id">
                        @foreach ($statuses as $status)
                            <option value="{{$status->id}}">{{$status->name}}</option>
                        @endforeach
                    </select>
                </div>
                <button type="submit" class="btn btn-primary">Изменить</button>
            </form>
        </div>
    </div>
@endsection

resources/views/transports/index.blade.php
@extends('transports.layout')
@section('content')
    <div class="container">
    <style>
        .uper {
            margin-top: 40px;
        }
    </style>
    <div class="uper">
        @if(session()->get('success'))
            <div class="alert alert-success">
                {{ session()->get('success') }}
            </div><br/>
        @endif
            <a href="{{route('transportt.create')}}"><button class="btn btn-success">Создать</button></a>
        <table class="table table-striped">
            <thead>
            <tr>
                <td>Марка</td>
                <td>Пробег</td>
                <td>Водитель</td>
                <td>Тип транспорта</td>
                <td>Статус</td>
                <td></td>
                <td></td>
            </tr>
            </thead>
            <tbody>
            @foreach($transports['transports'] as $transport)
                <tr>
                    <td>{{$transport->brand}}</td>
                    <td>{{$transport->mileage}}</td>
                    <td>{{App\Driver::find($transport->driver_id)['name']}}</td>
                    <td>{{App\TransportType::find($transport->type_id)['name']}}</td>
                    <td>{{App\TransportStatus::find($transport->status_id)['name']}}</td>
                    <td><a href="{{ route('transportt.edit',$transport->id)}}" class="btn btn-primary">Изменить</a>
                    </td>
                    <td>
                        <form action="{{ route('transportt.destroy', $transport->id)}}" method="post">
                            @csrf
                            @method('DELETE')
                            <button class="btn btn-danger" type="submit">Удалить</button>
                        </form>
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>
    </div>
    </div>

@endsection

resources/views/transports/layout.blade.php
@extends('layouts.app')